apiVersion: apps/v1
kind: Deployment
metadata:
 name: analysis
spec:
 replicas: 1
 selector:
  matchLabels:
   app: analysis
 template:
  metadata: 
   labels:
    app: analysis
  spec:
   containers:
    - name: analysis
      image: process
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
