apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq

