apiVersion: apps/v1
kind: Deployment
metadata:
 name: rss
spec:
 selector:
  matchLabels:
   app: rss
 template:
  metadata: 
   labels:
    app: rss
  spec:
   containers:
    - name: rss
      image: rss
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
