apiVersion: apps/v1
kind: Deployment
metadata:
 name: twitter
spec:
 selector:
  matchLabels:
   app: twitter
 template:
  metadata: 
   labels:
    app: twitter
  spec:
   containers:
    - name: twitter
      image: twitter
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
