apiVersion: apps/v1
kind: Deployment
metadata:
 name: web
spec:
 #front end is stateless, drawing it's data commonly from the database, so candidate for repl set
 replicas: 1
 selector:
  matchLabels:
   app: web
 template:
  metadata: 
   labels:
    app: web
  spec:
   containers:
    - name: web
      image: web
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
      ports:
       - containerPort: 5000
